### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "keosha",
  "email": "keosha@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "amanda@example.com",
  "password": "password"
}